# Abstract {.unnumbered} 

Categorical data, particularly when involving ordinal responses, plays a crucial role in fields such as social sciences and finance, where capturing the inherent ordering of variables can lead to more meaningful inferences of the underlying distributions. A key challenge in analyzing such data lies in exploring the regression dependence structures among variables. While many model-based approaches have been developed to examine these structures, there remains a scarcity of model-free methods. Wei & Kim (2021) addressed this gap by introducing SCCRAM, a novel model-free measure based on the checkerboard copula, capable of identifying and quantifying regression dependence in multivariate categorical data with ordinal and nominal variables. This work builds on their contribution by developing scalable R and Python packages for SCCRAM, employing parallel computing to enhance accessibility and efficiency in large-scale data analysis. Initial simulations demonstrate the effectiveness of these implementations, offering researchers a robust tool for exploratory modeling and further exploration of regression dependence structures in categorical datasets for this use-case.


# Acknowledgements {.unnumbered} 

I would like to thank everyone who made my experience nothing short of amazing during my thesis journey. Firstly, I'd like to convey my gratitude to Professor Shu-Min Liao for advising me through this journey, and for believing in me to take on statistical software component of her most recent research work along with her collaborators. From my first research experience on campus building R-Blocks, she played a pivotal role in my journey.

I am also incredibly grateful to my college advisor, and statistics major advisor, Professor Nicholas Horton for always advocating for me and for supporting me throughout the Amherst College experience. I would also like to thank Professor Jun Ishii for teaching me Advanced Econometrics, which helped me gain a really clear understanding on the foundational tools on which I was able to build on in my work.

Finally, I would like to thank my friends and family for their constant belief in my abilities. Special thanks to my mom, dad, sister, grandfather, and grandmother for lending me and making me capable for this opportunity to study abroad. Last, but not the least, I would like to thank my friends, peers, and colleagues on campus, who took courses, worked, and played sports with me. This journey of academic, personal, and professional growth wouldn't be possible without their support.   




<!--
The following line is required to transition from roman numeral page numbering to regular page numbering. Do not edit or remove. 
-->
\cleardoublepage\pagenumbering{arabic}\setcounter{page}{1}